### ISSUE TITLE
few errors i came across

### ISSUE THREAD

**Issue by pickeld** [dimagoltsman/ha-custom-component-ituran#1]
'''
2018-08-19 18:29:37 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 326, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 217, in async_update_ha_state
    attr = self.state_attributes or {}
  File "/config/custom_components/ituran.py", line 98, in state_attributes
    "milage" : self._milage
AttributeError: 'Ituran' object has no attribute '_milage'

2018-08-19 18:30:43 ERROR (MainThread) [homeassistant.core] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/util/__init__.py", line 325, in wrapper
    result = method(*args, **kwargs)
TypeError: update() takes 1 positional argument but 2 were given
2018-08-19 18:30:43 ERROR (MainThread) [homeassistant.core] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/util/__init__.py", line 325, in wrapper
    result = method(*args, **kwargs)
TypeError: update() takes 1 positional argument but 2 were given

2018-08-19 18:30:50 ERROR (MainThread) [homeassistant.core] Timer got out of sync. Resetting
2018-08-19 18:30:55 ERROR (MainThread) [frontend.js.latest.201808161] https://DOMAIN.COM/local/content-card-ituran.js:27:24 Uncaught TypeError: Cannot read property 'attributes' of undefined
2018-08-19 18:30:57 ERROR (MainThread) [frontend.js.latest.201808161] https://DOMAIN.COM/frontend_latest/app-2ca9355c.js:2:12805 Uncaught TypeError: Cannot read property 'attributes' of null
2018-08-19 18:31:03 ERROR (MainThread) [frontend.js.latest.201808161] https://DOMAIN.COM/frontend_latest/app-2ca9355c.js:2:12805 Uncaught TypeError: Cannot read property 'attributes' of null
2018-08-19 18:31:04 ERROR (MainThread) [frontend.js.latest.201808161] https://DOMAIN.COM/local/content-card-ituran.js:27:24 Uncaught TypeError: Cannot read property 'attributes' of undefined
2018-08-19 18:31:06 ERROR (MainThread) [frontend.js.latest.201808161] https://DOMAIN.COM/frontend_latest/app-2ca9355c.js:2:12805 Uncaught TypeError: Cannot read property 'attributes' of null
2018-08-19 18:31:09 ERROR (MainThread) [frontend.js.latest.201808161] https://DOMAIN.COM/local/content-card-ituran.js:27:24 Uncaught TypeError: Cannot read property 'attributes' of undefined
2018-08-19 18:31:17 ERROR (MainThread) [frontend.js.latest.201808161] https://DOMAIN.COM/local/content-card-ituran.js:27:24 Uncaught TypeError: Cannot read property 'attributes' of undefined
2018-08-19 18:31:21 ERROR (MainThread) [frontend.js.latest.201808161] https://DOMAIN.COM/local/content-card-ituran.js:27:24 Uncaught TypeError: Cannot read property 'attributes' of undefined
'''

**Comment by dimagoltsman** [comment]
Please add your ituran config

**Comment by pickeld** [comment]
configuration.yaml
```
frontend:
  extra_html_url:
    - /local/custom_ui/state-card-ituran.html

ituran:
  sportage:
    name: Sportage
    username: 'uname'
    password: 'password'
```
"\\192.168.0.250\config\custom_components\ituran.py"
"\\192.168.0.250\config\www\custom_ui\state-card-ituran.html"

**Comment by dimagoltsman** [comment]
Try accessing with the browser

https://www.ituran.com/ituranmobileservice/mobileservice.asmx/GetUserPlatforms?UserName=YourUsername&GetAddress=True&Password=YourPassword

**Comment by pickeld** [comment]
I get a xml file with the data

**Comment by dimagoltsman** [comment]
Correct data? No errors?

**Comment by pickeld** [comment]
Yes. No errors . An xml with lots of data

**Comment by dimagoltsman** [comment]
What ha version? And is it lovelace or groups?

**Comment by pickeld** [comment]
hass.io 0.76.1
i've tried lovelace and groups as well.


```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<ServiceListPlatformsDetails xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.ituran.com/IturanMobileService">
<ReturnCode>OK</ReturnCode>
<Username>myUsername</Username>
<VehList>
<Veh>
<PlatformId>xxxx</PlatformId>
<Plate>xxx</Plate>
<Label>xxx</Label>
<Symbol/>
<Lat>xx.xxx</Lat>
<Lon>xx.xxx</Lon>
<Speed>0</Speed>
<LastMileage>2981.70</LastMileage>
<Head>254</Head>
<Address>myAddress</Address>
<Date>2018-08-21T09:03:48</Date>
<driverId>-1</driverId>
<driverName/>
<driverphone/>
<IsSafety>false</IsSafety>
<IsRfUnit>false</IsRfUnit>
<Units>
<Unit>
<PocsagStr>xxxxx</PocsagStr>
<Services>
<Service>
<ProductName>ituran app</ProductName>
</Service>
</Services>
</Unit>
</Units>
</Veh>
</VehList>
<Timelast>
total=40<br>Details: build_platform_data_dictionary= 0<br> load_platformId_platLabel= 15953<br> load_password_dictionary= 5528<br> load_username_cusid_dic= 1826<br> load_Customer_user_Rules= 10078<br> GetStatuses_dic= 18112<br> Getcontacts_dic= 216<br> load_platformId_PlatformDetails_dic= 1224<br> m_platformID_CusID_isSafety_dic= 6018<br> m_productId_IturanApp= 4<br> GetUserPlatformsDictionary= 38667<br> GetUserContactsDictionary= 2663<br> build m_UserId_CusId_dic= 4170<br> GetUserIsUsingMilesDic= 4407<br> GetUsernameUseridDictionary= 8190<br> rebuild_dictionaries_for_leading_pocsag= 1898<br> get_cus_pocsags_dictionary= 7802<br> get_pocsag_pocsagstr_dictionary= 4670<br> pocsag_profile_dictionary= 23062<br> build_platform_group= 16971<br> create_rule_definitions_dic= 15077<br> build_AcceptedUserIds_dictionary= 128<br> force_non_web_mode_for_reports= 0 pocsag_cusId_product_dic= 8277<br>
</Timelast>
<HasToChangePassword>false</HasToChangePassword>
<UrlRedirectMode>OFF</UrlRedirectMode>
<UrlToRedirectTo/>
</ServiceListPlatformsDetails>
ccc { } ccc.ccc--converted { animation: ccc 0.7s ease-in-out; } @-webkit-keyframes ccc { from { background-color: yellow; } to { background-color: rgba(255, 255, 255, 0); } }
```


here's the returned xml
is it valid? look at the bottom

**Comment by dimagoltsman** [comment]
I think there is some race condition  will be mext to a computer soon to fix it

**Comment by pickeld** [comment]
Thank you for your time and help

**Comment by dimagoltsman** [comment]
update your ituran.py (i added a fix) and restart HA

**Comment by pickeld** [comment]
Thank you. Everything works just fine.

**Comment by dimagoltsman** [comment]
:)
